SYMBOL(Sequence)
SYMBOL(List)

SYMBOL(True)
SYMBOL(False)
SYMBOL(Null)

SYMBOL(Blank)
SYMBOL(BlankSequence)
SYMBOL(BlankNullSequence)
SYMBOL(Pattern)
SYMBOL(PatternTest)
SYMBOL(Condition)
SYMBOL(Optional)
SYMBOL(Alternatives)
SYMBOL(Repeated)

SYMBOL(Verbatim)
SYMBOL(OptionsPattern)
SYMBOL(Slot)
SYMBOL(SlotSequence)
SYMBOL(Function)
SYMBOL(Module)

SYMBOL(StateModuleNumber)
