// note: having List here first should guarantee that Lists
// are efficiently handled if they occur as "default" case
// in switch statements.

SYMBOL(List)
SYMBOL(Sequence)
SYMBOL(Rule)
SYMBOL(RuleDelayed)

SYMBOL(True)
SYMBOL(False)
SYMBOL(Null)
SYMBOL(All)

SYMBOL(Blank)
SYMBOL(BlankSequence)
SYMBOL(BlankNullSequence)
SYMBOL(Pattern)
SYMBOL(PatternTest)
SYMBOL(Condition)
SYMBOL(Optional)
SYMBOL(Alternatives)
SYMBOL(Repeated)
SYMBOL(RepeatedNull)
SYMBOL(Except)
SYMBOL(OptionsPattern)
SYMBOL(Shortest)
SYMBOL(Longest)
SYMBOL(StringExpression)

SYMBOL(Slot)
SYMBOL(SlotSequence)
SYMBOL(Function)
SYMBOL(OptionValue)
SYMBOL(Module)
SYMBOL(Verbatim)

SYMBOL(_Symbol)
SYMBOL(Integer)
SYMBOL(Rational)
SYMBOL(Real)
SYMBOL(Complex)
SYMBOL(String)
SYMBOL(Automatic)

SYMBOL(LessEqual)

SYMBOL(Plus)
SYMBOL(Times)
SYMBOL(Divide)
SYMBOL(Minus)
SYMBOL(Power)
SYMBOL(Log)
SYMBOL(Factorial)
SYMBOL(Gamma)
SYMBOL(Abs)
SYMBOL(Conjugate)

SYMBOL(E)
SYMBOL(Pi)
SYMBOL(EulerGamma)
SYMBOL(I)

SYMBOL(Cos)
SYMBOL(Sin)
SYMBOL(Tan)

SYMBOL(Infinity)
SYMBOL(DirectedInfinity)
SYMBOL(ComplexInfinity)
SYMBOL(Indeterminate)
SYMBOL(GoldenRatio)
SYMBOL(MachinePrecision)
SYMBOL(Catalan)

SYMBOL(InputForm)
SYMBOL(OutputForm)
SYMBOL(StandardForm)
SYMBOL(FullForm)
SYMBOL(TraditionalForm)
SYMBOL(TeXForm)
SYMBOL(MathMLForm)
SYMBOL(PrecedenceForm)

SYMBOL(MakeBoxes)
SYMBOL(Row)
SYMBOL(Superscript)
SYMBOL(RowBox)
SYMBOL(SuperscriptBox)
SYMBOL(StyleBox)
SYMBOL(ShowStringCharacters)
SYMBOL(ImageSizeMultipliers)

SYMBOL(HoldForm)
SYMBOL(Infix)
SYMBOL(Prefix)
SYMBOL(Postfix)
SYMBOL(Left)
SYMBOL(Right)
SYMBOL(None)
SYMBOL(NonAssociative)

SYMBOL(StartOfString)
SYMBOL(EndOfString)
SYMBOL(StartOfLine)
SYMBOL(EndOfLine)

SYMBOL(Whitespace)
SYMBOL(WordBoundary)
SYMBOL(WhitespaceCharacter)
SYMBOL(DigitCharacter)
SYMBOL(LetterCharacter)
SYMBOL(WordCharacter)
SYMBOL(HexidecimalCharacter)

SYMBOL(NumberForm)
SYMBOL(NumberSigns)
SYMBOL(ExponentStep)
SYMBOL(ExponentFunction)
SYMBOL(DigitBlock)
SYMBOL(NumberSeparator)
SYMBOL(NumberPadding)
SYMBOL(SignPadding)
SYMBOL(NumberPoint)
SYMBOL(NumberFormat)
SYMBOL(NumberMultiplier)

SYMBOL(Orderless)
SYMBOL(Flat)
SYMBOL(OneIdentity)
SYMBOL(Listable)
SYMBOL(Constant)
SYMBOL(NumericFunction)
SYMBOL(Protected)
SYMBOL(Locked)
SYMBOL(ReadProtected)
SYMBOL(HoldFirst)
SYMBOL(HoldRest)
SYMBOL(HoldAll)
SYMBOL(HoldAllComplete)
SYMBOL(NHoldFirst)
SYMBOL(NHoldRest)
SYMBOL(NHoldAll)
SYMBOL(SequenceHold)

SYMBOL(Evaluate)
SYMBOL(Unevaluated)

SYMBOL(Graphics)

SYMBOL(General)
SYMBOL(MessageName)

SYMBOL(StateLine)
SYMBOL(StateModuleNumber)
